### ISSUE TITLE
Docs for installing on existing DAO

### ISSUE THREAD

**Issue by shinsyotta** [PeterMPhillips/aragon-token-wrapper#1]
Specifically thinking about an Aragon DAO that was created via the UI on the main Aragon site.  Point me in the right direction and I'll contribute some docs.

**Comment by PeterMPhillips** [comment]
Sorry @shinsyotta the default Token Manager app doesn't have a way to call the changeController() function on the MiniMe token. Once it's set you can't switch it to this contract.
